///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String animationBg1 = 'assets/animation/bg-1.json';
  static const String animationBg2 = 'assets/animation/bg-2.json';
  static const String animationBg3 = 'assets/animation/bg-3.json';
  static const String animationCar = 'assets/animation/car.json';
  static const String animationLoading = 'assets/animation/loding.json';

  static const String fontsPacificoRegular =
      'assets/fonts/Pacifico-Regular.ttf';
  static const String fontsPoppinsRegular = 'assets/fonts/Poppins-Regular.ttf';
  static const String fontsSairaCondensedRegular =
      'assets/fonts/Saira_Condensed-Regular.ttf';
  static const String imagesAppleIcon = 'assets/images/appleIcon.svg';
  static const String imagesBell = 'assets/images/bell.svg';
  static const String imagesBueaty = 'assets/images/bueaty.svg';
  static const String imagesCart = 'assets/images/cart.svg';
  static const String imagesClothing = 'assets/images/clothing.svg';
  static const String imagesFitness = 'assets/images/fitness.svg';
  static const String imagesForgetPass = 'assets/images/forgetPass.png';
  static const String imagesGaming = 'assets/images/gaming.svg';
  static const String imagesGoogleIcon = 'assets/images/googleIcon.svg';
  static const String imagesHome = 'assets/images/home.svg';
  static const String imagesImageSlider1 = 'assets/images/image_slider_1.png';
  static const String imagesLiving = 'assets/images/living.svg';
  static const String imagesLogoIcon = 'assets/images/logoIcon.png';
  static const String imagesOnBoarding1 = 'assets/images/onBoarding1.png';
  static const String imagesOnBoarding2 = 'assets/images/onBoarding2.png';
  static const String imagesOnBoarding3 = 'assets/images/onBoarding3.png';
  static const String imagesOnBoardingJson2 =
      'assets/images/onBoardingJson2.json';
  static const String imagesOnBording1 = 'assets/images/onBording1.json';
  static const String imagesProfile = 'assets/images/profile.svg';
  static const String imagesSaved = 'assets/images/saved.svg';
  static const String imagesSchool = 'assets/images/school.svg';
  static const String imagesSearch = 'assets/images/search.svg';
  static const String imagesSearchNotFound =
      'assets/images/search_not_found.png';
  static const String imagesStar = 'assets/images/star.svg';
  static const String imagesSuccess = 'assets/images/Success.png';
  static const String imagesVector = 'assets/images/Vector.svg';
  static const String imagesVector2 = 'assets/images/Vector2.svg';
  static const String langAr = 'assets/lang/ar.json';
  static const String langEn = 'assets/lang/en.json';
  static const String svgsBell = 'assets/svgs/bell.svg';
  static const String svgsBellDuotone = 'assets/svgs/Bell-duotone.svg';
  static const String svgsBueaty = 'assets/svgs/bueaty.svg';
  static const String svgsCardDuotone = 'assets/svgs/Card-duotone.svg';
  static const String svgsCart = 'assets/svgs/cart.svg';
  static const String svgsCircleLock01 = 'assets/svgs/circle-lock-01.svg';
  static const String svgsClothing = 'assets/svgs/clothing.svg';
  static const String svgsDiscountDuotone = 'assets/svgs/Discount-duotone.svg';
  static const String svgsExist = 'assets/svgs/exist.svg';
  static const String imagesDropDown = 'assets/images/dropDown.png';

  static const String svgsFitness = 'assets/svgs/fitness.svg';
  static const String svgsGaming = 'assets/svgs/gaming.svg';
  static const String svgsHeartDuotone = 'assets/svgs/Heart-duotone.svg';
  static const String svgsHome = 'assets/svgs/home.svg';
  static const String svgsLiving = 'assets/svgs/living.svg';
  static const String svgsLocationDuotone = 'assets/svgs/Location-duotone.svg';
  static const String svgsLogout05 = 'assets/svgs/logout-05.svg';
  static const String svgsOrderLight = 'assets/svgs/order-light.svg';
  static const String svgsProfile = 'assets/svgs/profile.svg';
  static const String svgsSaved = 'assets/svgs/saved.svg';
  static const String svgsSchool = 'assets/svgs/school.svg';
  static const String svgsSearch = 'assets/svgs/search.svg';
  static const String svgsSearchlens = 'assets/svgs/searchlens.svg';
  static const String svgsStar = 'assets/svgs/star.svg';
  static const String svgsUserAdd01 = 'assets/svgs/user-add--01.svg';
  static const String svgsUserDuotone = 'assets/svgs/User-duotone.svg';
  static const String svgsVector = 'assets/svgs/Vector.svg';
  static const String svgsProduct = 'assets/svgs/product.svg';
  static const String svgsItem = 'assets/svgs/item.svg';
}
